/* Change this file to get your personal Portfolio */

// To change portfolio colors globally go to the  _globalColor.scss file

import emoji from "react-easy-emoji";

// Summary And Greeting Section

const illustration = {
  animated: true // Set to false to use static SVG
};

const greeting = {
  username: "Shushant Pudasaini",
  title: "Hi all, I'm Shushant",
  subTitle: emoji(
    "An experienced AI Developer 🚀 having an experience of building AI services and products specializing in NLP."
  ),
  resumeLink:
    "https://drive.google.com/file/d/18KdlKgq-3R9HNmBj-gWG9zxTKNgJTvjp/view?usp=sharing", // Set to empty to hide the button
  displayGreeting: true // Set false to hide this section, defaults to true
};

// Social Media Links

const socialMediaLinks = {
  github: "https://github.com/pudasainishushant",
  linkedin: "https://www.linkedin.com/in/shushant-pudasaini-baa7b0134/",
  gmail: "shushanta574@gmail.com",
  gitlab: "https://gitlab.com/saadpasta",
  facebook: "https://gitlab.com/shusrulz",
  medium: "https://medium.com/@shushanta574",
  // stackoverflow: "https://stackoverflow.com/users/10422806/saad-pasta",
  // Instagram, Twitter and Kaggle are also supported in the links!
  // To customize icons and social links, tweak src/components/SocialMedia
  display: true // Set true to display this section, defaults to false
};

// Skills Section

const skillsSection = {
  title: "What I do",
  subTitle: "Computer Engineer with expertise in Artificial Intelligence, Data Science and Robotics domain.",
  skills: [
    emoji(
      "⚡ Develop NLP based services like chatbots, text summarizer in multi-lingual domain"
    ),
    emoji("⚡ Develop computer vision based services like face attendance, custom object detector and many others"),
    emoji(
      "⚡ Deployment of AI based services in production"
    )
  ],

  /* Make Sure to include correct Font Awesome Classname to view your icon
https://fontawesome.com/icons?d=gallery */

  softwareSkills: [
    {
      skillName: "aws",
      fontAwesomeClassname: "fab fa-aws"
    },
    {
      skillName: "python",
      fontAwesomeClassname: "fab fa-python"
    },
    {
      skillName: "docker",
      fontAwesomeClassname: "fab fa-docker"
    },
    {
      skillName: "git",
      fontAwesomeClassname: "fab fa-git"
    },
    {
      skillName: "linux",
      fontAwesomeClassname: "fab fa-linux"
    }
  ],
  display: true // Set false to hide this section, defaults to true
};

// Education Section

const educationInfo = {
  display: true, // Set false to hide this section, defaults to true
  schools: [
    {
      schoolName: "Advanced College of Engineering and Management",
      logo: require("./assets/images/acem_logo.png"),
      subHeader: "Bachelor in Computer Engineering",
      duration: "September 2014 - April 2018"
    }
  ]
};

// Your top 3 proficient stacks/tech experience

const techStack = {
  viewSkillBars: true, //Set it to true to show Proficiency Section
  experience: [
    {
      Stack: "AI Services Deployment", //Insert stack or technology you have experience in
      progressPercentage: "60%" //Insert relative proficiency in percentage
    },
    {
      Stack: "AI Services Development",
      progressPercentage: "80%"
    },
    {
      Stack: "Python",
      progressPercentage: "70%"
    }
  ],
  displayCodersrank: false // Set true to display codersrank badges section need to changes your username in src/containers/skillProgress/skillProgress.js:17:62, defaults to false
};

// Work experience section

const workExperiences = {
  display: true, //Set it to true to show workExperiences Section
  experience: [
    {
      role: "Data Analyst",
      company: "Datalytics Pvt Ltd",
      companylogo: require("./assets/images/datalytics_logo.png"),
      date: "June 2018 – Present",
      desc: "Worked as Data Analyst mainly playing with the data generated by the inhouse product of the company.",
      descBullets: [
        "Data visualization using MATLAB",
        "Data Analysis using SPSS tool",
        "Prepared technical research papers using LATEX.",
        "Developed automation scripts using Python"
      ]
    },
    {
      role: "AI Consulant",
      company: "ITSutra",
      companylogo: require("./assets/images/itsutra_logo.png.png"),
      date: "May 2017 – May 2018",
      desc: "Worked as freelance AI consultant to develop inhouse face recognition system for identifying the guests and employee of the company in office premises",
      descBullets: [
        "Developed web application using Django for providing smart attendance system using face-api provided by Microsoft Azure Cognitive service",
        "Consult and Supervise on AI projects"
      ]
    },
    {
      role: "AI Team Lead",
      company: "Infodevelopers Pvt Ltd",
      companylogo: require("./assets/images/inodevelopers_logo.png"),
      date: "Jan 2015 – Sep 2015",
      desc: "Working as AI team lead to develop and mantain AI services like chatbots, applicant tracking systems, face attendance system",
      descBullets: [
        "Developed several chatbots for banking organizations, and government projects.",
        "Built inhouse attendance system using face recognition (currently being used in the company through raspberry pi and real sense camera",
        "Worked in data science-based solutions for government websites ",
        "Deployment of AI products using technologies such as Flask, Docker, AWS, nginx"
      ]
    },
    {
      role: "AI Team Lead",
      company: "National Innovation Center",
      companylogo: require("./assets/images/nic_logo.png"),
      date: "May 2017 – May 2018",
      desc: "Working as AI team lead to develop computer vision services like face recognition, object detection and running such services in edge devices like Raspeberry Pi and Jetson Nano for robots and drones.",
      descBullets: [
        "Working in MINA framework for leveraging computer vision based solutions like object detection, object tracking, face recognition for robotics projects in NIC"
      ]
    },
    {
      role: "AI Lecturer",
      company: "Herald College",
      companylogo: require("./assets/images/herald_college_logo.png"),
      date: "May 2017 – May 2018",
      desc: "Worked as a part time lecturer to give lectures on Artificial Intelligence and  supervise students in thier AI based final thesis"
    }
  ]
};

/* Your Open Source Section to View Your Github Pinned Projects
To know how to get github key look at readme.md */

const openSource = {
  showGithubProfile: "true", // Set true or false to show Contact profile using Github, defaults to true
  display: true // Set false to hide this section, defaults to true
};

// Some big projects you have worked on

const bigProjects = {
  title: "Big Projects",
  subtitle: "SOME STARTUPS AND COMPANIES THAT I HELPED TO CREATE THEIR TECH",
  projects: [
    {
      image: require("./assets/images/dolphwin.png"),
      projectName: "Dolphwin",
      projectDesc: "Applicant Tracking System supported by NLP backend engine with NLP services like Resume Parsing, chatbot, job seeker and job profile match making",
      footerLink: [
        {
          name: "Visit Website",
          url: "https://dolphwin.com/#/"
        }
        //  you can add extra buttons here.
      ]
    },
    {
      image: require("./assets/images/rapi.png"),
      projectName: "Rapi Money",
      projectDesc: "Banking system for taking loans supported by several AI features like chatbot, profile picture validation ",
      footerLink: [
        {
          name: "Visit Website",
          url: "http://www.rapimoney.com/"
        }
      ]
    }
  ],
  display: true // Set false to hide this section, defaults to true
};

// Achievement Section
// Include certificates, talks etc

const achievementSection = {
  title: emoji("Achievements And Certifications 🏆 "),
  subtitle:
    "Achievements, Certifications, Award Letters and Some Cool Stuff that I have done !",

  achievementsCards: [
    {
      title: "Certification in Natural Language Processing in Tensorflow from Coursera",
      subtitle:
        "Certified as NLP developer using Tenorflow from Coursera",
      image: require("./assets/images/coursera.png"),
      footerLink: [
        {
          name: "Certification",
          url: "https://drive.google.com/file/d/1iNVHqvTL9QE3ffLtBFKRkoeg8w6Y8bKN/view?usp=sharing"
        }
      ]
    },
    {
      title: "Python",
      subtitle:
        "Certification in Python Data Structures",
      image: require("./assets/images/lynda.png"),
      footerLink: [
        {
          name: "Certification",
          url: "https://drive.google.com/file/d/1qb2MjSyR0lP0dstH9yf5i8u0kcpbCxvn/view?usp=sharing"
        }
      ]
    },

    {
      title: "Google Scholar ",
      subtitle: "Publised research papers in Google Scholar",
      image: require("./assets/images/google_scholar.png"),
      footerLink: [
        {name: "Research paper on Information Extraction", url: "https://link.springer.com/chapter/10.1007/978-981-16-2126-0_54"},
        {
          name: "Research Paper on Gale Shapely Algorithm",
          url: "https://link.springer.com/chapter/10.1007/978-981-16-2126-0_55"
        }
      ]
    }
  ],
  display: true // Set false to hide this section, defaults to true
};

// Blogs Section

const blogSection = {
  title: "Blogs",
  subtitle:
    "With Love for Developing cool stuff, I love to write and teach others what I have learnt.",

  blogs: [
    {
      url: "https://medium.com/@shushanta574/is-the-deep-learning-hype-real-and-will-deep-learning-replace-machine-learning-algorithms-2a5911aab2f1",
      title: "Is the deep learning hype real and will deep learning replace machine learning algorithms?",
      description:
        "I discuss about what are the prospects of Deep Learning in the AI space and is the hype sorrounding deep learning worth it?"
    },
    {
      url: "https://medium.com/@shushanta574/bert-4810545a53b7",
      title: "How does BERT work and what are the use cases of BERT ? ",
      description:
        "BERT is the latest breakdown in NLP space. In this blog, I discuss about the BERT algorthm and its use cases. "
    },
    {
      url: "https://medium.com/@shushanta574/develop-nepali-word-piece-sub-word-tokenizer-using-huggingface-tokenizers-library-80ae4d0500c6",
      title: "Develop Nepali Word Piece Sub word Tokenizer using huggingface tokenizers library",
      description:
        "Multilingual NLP can be difficult. Learn how to develop custom sub word tokenizer for devanagari data in this blog."
    },
    {
      url: "https://medium.com/@shushanta574/what-are-the-challenges-faced-in-machine-learning-and-data-mining-56e11131b4f",
      title: "What are the challenges faced in machine learning and data mining?",
      description:
        "We face different challenges in machine learning projects. Learn to deal with those challenges."
    }
  ],
  display: true // Set false to hide this section, defaults to true
};

// Talks Sections

const talkSection = {
  title: "TALKS",
  subtitle: emoji(
    "I LOVE TO SHARE MY LIMITED KNOWLEDGE AND GET A SPEAKER BADGE 😅"
  ),

  talks: [
    {
      title: "Build Actions For Google Assistant",
      subtitle: "Codelab at GDG DevFest Karachi 2019",
      slides_url: "https://bit.ly/saadpasta-slides",
      event_url: "https://www.facebook.com/events/2339906106275053/"
    }
  ],
  display: false // Set false to hide this section, defaults to true
};

// Podcast Section

const podcastSection = {
  title: emoji("Podcast 🎙️"),
  subtitle: "I LOVE TO TALK ABOUT MYSELF AND TECHNOLOGY",

  // Please Provide with Your Podcast embeded Link
  podcast: [
    "https://anchor.fm/codevcast/embed/episodes/DevStory---Saad-Pasta-from-Karachi--Pakistan-e9givv/a-a15itvo"
  ],
  display: false // Set false to hide this section, defaults to true
};

const contactInfo = {
  title: emoji("Contact Me ☎️"),
  subtitle:
    "Discuss a project or just want to say hi? My Inbox is open for all. Give me a call at +9779843698538 or email me @ shushanta574@gmail.com",
  number: "+9779843698538",
  email_address: "shushanta574@gmail.com"
};

// Twitter Section

const twitterDetails = {
  userName: "twitter", //Replace "twitter" with your twitter username without @
  display: false // Set true to display this section, defaults to false
};

export {
  illustration,
  greeting,
  socialMediaLinks,
  skillsSection,
  educationInfo,
  techStack,
  workExperiences,
  openSource,
  bigProjects,
  achievementSection,
  blogSection,
  talkSection,
  podcastSection,
  contactInfo,
  twitterDetails
};
